<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>MagicBytesValidator</PackageId>
        <Title>MagicBytesValidator</Title>
        <Description>Validate files based on mime types, file extensions and magic byte sequences.</Description>
        <PackageTags>mime mimetype mimetypes magic magicbyte magicbytes extension extensions file
            fileextension trapertoGmbH + TobiasJanssen
        </PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
